# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - idx61_arm_r_joint1
    - idx62_arm_r_joint2
    - idx63_arm_r_joint3
    - idx64_arm_r_joint4
    - idx65_arm_r_joint5
    - idx66_arm_r_joint6
    - idx67_arm_r_joint7
default_q: [
    0.0,0.0,0.0,0.0,0.0,0.0,0.0
]

acceleration_limits: [
   10,10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: idx01_body_joint1, rule: fixed, value: 0.3}
    - {name: idx02_body_joint2, rule: fixed, value: 0.52359877}
    - {name: idx11_head_joint1, rule: fixed, value: -0.0}
    - {name: idx12_head_joint2, rule: fixed, value: 0.2793}


# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - base_link:
    - "center": [-0.109, 0.0, 0.425]
      "radius": 0.15
    - "center": [-0.118, 0.0, 1.116]
      "radius": 0.15
    - "center": [-0.111, 0.0, 0.598]
      "radius": 0.15
    - "center": [-0.113, 0.0, 0.77]
      "radius": 0.15
    - "center": [-0.116, 0.0, 0.943]
      "radius": 0.15
  - body_link1:
    - "center": [0.13, 0.0, 0.0]
      "radius": 0.05
  - body_link2:
    - "center": [0.0, -0.147, 0.0]
      "radius": 0.08
    - "center": [0.003, -0.322, 0.0]
      "radius": 0.08
  - head_link2:
    - "center": [-0.017, 0.031, 0.0]
      "radius": 0.05
  - arm_r_base_link:
    - "center": [0.0, 0.0, 0.027]
      "radius": 0.03
  - arm_r_link1:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.073]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.033]
      "radius": 0.03
  - arm_r_link2:
    - "center": [0.0, -0.086, 0.0]
      "radius": 0.03
  - arm_r_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.141]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.03]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.084]
      "radius": 0.03
  - arm_r_link4:
    - "center": [0.0, -0.05, 0.0]
      "radius": 0.03
  - arm_r_link5:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.093]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.031]
      "radius": 0.03
  - arm_r_link6:
    - "center": [0.0, -0.065, 0.0]
      "radius": 0.03
  - arm_l_base_link:
    - "center": [0.0, 0.0, 0.027]
      "radius": 0.03
  - arm_l_link1:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.073]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.033]
      "radius": 0.03
  - arm_l_link2:
    - "center": [0.0, -0.086, 0.0]
      "radius": 0.03
  - arm_l_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.141]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.03]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.084]
      "radius": 0.03
  - arm_l_link4:
    - "center": [0.0, -0.05, 0.0]
      "radius": 0.03
  - arm_l_link5:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.093]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.031]
      "radius": 0.03
  - arm_l_link6:
    - "center": [0.0, -0.065, 0.0]
      "radius": 0.03
  - gripper_l_base_link:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.05]
      "radius": 0.02
    - "center": [0.0, -0.015, 0.03]
      "radius": 0.015
    - "center": [0.0, 0.015, 0.03]
      "radius": 0.015
    - "center": [-0.063, 0.01, 0.003]
      "radius": 0.01
    - "center": [-0.063, -0.01, 0.003]
      "radius": 0.01
    - "center": [-0.089, -0.01, 0.017]
      "radius": 0.01
    - "center": [-0.089, 0.01, 0.017]
      "radius": 0.01
  - gripper_l_inner_link1:
    - "center": [0.0, 0.003, -0.005]
      "radius": 0.01
    - "center": [0.0, 0.003, 0.005]
      "radius": 0.01
    - "center": [0.014, 0.012, -0.005]
      "radius": 0.00758
    - "center": [0.014, 0.012, 0.006]
      "radius": 0.00758
    - "center": [0.025, 0.019, 0.008]
      "radius": 0.00574
    - "center": [0.015, -0.008, 0.02]
      "radius": 0.005
    - "center": [0.015, -0.008, -0.02]
      "radius": 0.005
    - "center": [0.051, -0.008, 0.012]
      "radius": 0.005
    - "center": [0.051, -0.008, -0.012]
      "radius": 0.005
    - "center": [0.024, -0.008, 0.018]
      "radius": 0.005
    - "center": [0.033, -0.008, 0.016]
      "radius": 0.005
    - "center": [0.042, -0.008, 0.014]
      "radius": 0.005
    - "center": [0.024, -0.008, -0.018]
      "radius": 0.005
    - "center": [0.033, -0.008, -0.016]
      "radius": 0.005
    - "center": [0.042, -0.008, -0.014]
      "radius": 0.005
    - "center": [0.033, -0.008, 0.004]
      "radius": 0.005
    - "center": [0.033, -0.008, -0.004]
      "radius": 0.005
  - gripper_l_outer_link1:
    - "center": [0.007, -0.004, -0.004]
      "radius": 0.01
    - "center": [0.007, -0.004, 0.005]
      "radius": 0.01
    - "center": [0.033, -0.017, -0.004]
      "radius": 0.005
    - "center": [0.033, -0.017, 0.007]
      "radius": 0.005
    - "center": [0.015, -0.008, -0.004]
      "radius": 0.00841
    - "center": [0.028, -0.014, -0.004]
      "radius": 0.00595
    - "center": [0.015, -0.008, 0.005]
      "radius": 0.00841
    - "center": [0.028, -0.014, 0.007]
      "radius": 0.00595
    - "center": [0.015, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.015, 0.008, -0.02]
      "radius": 0.005
    - "center": [0.049, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.049, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, -0.02]
      "radius": 0.005
    - "center": [0.032, 0.007, -0.02]
      "radius": 0.005
    - "center": [0.04, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.007, 0.02]
      "radius": 0.005
    - "center": [0.04, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, 0.01]
      "radius": 0.005
    - "center": [0.024, 0.008, -0.01]
      "radius": 0.005
    - "center": [0.032, 0.007, 0.0]
      "radius": 0.005
  - gripper_l_inner_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.008
    - "center": [0.017, -0.014, 0.0]
      "radius": 0.008
    - "center": [0.009, -0.007, 0.0]
      "radius": 0.008
  - gripper_l_outer_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.008
    - "center": [0.018, 0.014, 0.0]
      "radius": 0.008
    - "center": [0.009, 0.007, 0.0]
      "radius": 0.008
  - gripper_l_inner_link4:
    - "center": [0.013, -0.008, 0.004]
      "radius": 0.008
    - "center": [0.013, -0.008, -0.004]
      "radius": 0.008
    - "center": [0.046, -0.021, -0.0]
      "radius": 0.002
    - "center": [0.042, -0.02, 0.008]
      "radius": 0.002
    - "center": [0.042, -0.02, -0.008]
      "radius": 0.002
    - "center": [0.024, -0.013, -0.006]
      "radius": 0.00566
    - "center": [0.032, -0.016, -0.007]
      "radius": 0.004
    - "center": [0.038, -0.018, -0.008]
      "radius": 0.00283
    - "center": [0.024, -0.013, 0.006]
      "radius": 0.00566
    - "center": [0.032, -0.016, 0.007]
      "radius": 0.004
    - "center": [0.038, -0.018, 0.008]
      "radius": 0.00283
    - "center": [0.044, -0.02, 0.004]
      "radius": 0.002
    - "center": [0.044, -0.02, -0.004]
      "radius": 0.002
    - "center": [0.036, -0.018, -0.0]
      "radius": 0.004
  - gripper_l_outer_link4:
    - "center": [0.005, 0.005, 0.0]
      "radius": 0.01
    - "center": [0.014, 0.007, -0.022]
      "radius": 0.008
    - "center": [0.014, 0.007, 0.022]
      "radius": 0.008
    - "center": [0.046, 0.021, -0.0]
      "radius": 0.0013
    - "center": [0.033, 0.019, -0.025]
      "radius": 0.004
    - "center": [0.033, 0.019, 0.025]
      "radius": 0.004
    - "center": [0.021, 0.011, -0.0]
      "radius": 0.00665
    - "center": [0.032, 0.016, -0.0]
      "radius": 0.00442
    - "center": [0.039, 0.018, -0.0]
      "radius": 0.00294
    - "center": [0.043, 0.02, -0.0]
      "radius": 0.00196
    - "center": [0.038, 0.02, -0.016]
      "radius": 0.00302
    - "center": [0.042, 0.021, -0.009]
      "radius": 0.00228
    - "center": [0.044, 0.021, -0.004]
      "radius": 0.00172
    - "center": [0.038, 0.02, 0.016]
      "radius": 0.00302
    - "center": [0.042, 0.021, 0.009]
      "radius": 0.00228
    - "center": [0.044, 0.021, 0.004]
      "radius": 0.00172
    - "center": [0.025, 0.014, 0.025]
      "radius": 0.00566
    - "center": [0.025, 0.014, -0.025]
      "radius": 0.00566
    - "center": [0.028, 0.016, 0.014]
      "radius": 0.00516
    - "center": [0.028, 0.016, -0.014]
      "radius": 0.00516
  - gripper_l_inner_link2:
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.005
    - "center": [0.033, -0.011, -0.012]
      "radius": 0.005
    - "center": [0.033, -0.011, 0.012]
      "radius": 0.005
    - "center": [0.0, 0.0, -0.01]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.005
    - "center": [0.008, -0.003, -0.018]
      "radius": 0.005
    - "center": [0.016, -0.005, -0.016]
      "radius": 0.005
    - "center": [0.024, -0.008, -0.014]
      "radius": 0.005
    - "center": [0.008, -0.003, 0.018]
      "radius": 0.005
    - "center": [0.016, -0.005, 0.016]
      "radius": 0.005
    - "center": [0.024, -0.008, 0.014]
      "radius": 0.005
    - "center": [0.033, -0.011, -0.004]
      "radius": 0.005
    - "center": [0.033, -0.011, 0.004]
      "radius": 0.005
    - "center": [0.011, -0.004, -0.009]
      "radius": 0.005
    - "center": [0.022, -0.007, 0.001]
      "radius": 0.005
    - "center": [0.011, -0.004, 0.009]
      "radius": 0.005
    - "center": [0.022, -0.007, -0.001]
      "radius": 0.005
  - gripper_l_outer_link2:
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.009, -0.02]
      "radius": 0.005
    - "center": [0.032, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, -0.01]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.005
    - "center": [0.008, 0.002, -0.02]
      "radius": 0.005
    - "center": [0.016, 0.004, -0.02]
      "radius": 0.005
    - "center": [0.024, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.008, 0.002, 0.02]
      "radius": 0.005
    - "center": [0.016, 0.004, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.009, -0.01]
      "radius": 0.005
    - "center": [0.032, 0.009, 0.0]
      "radius": 0.005
    - "center": [0.032, 0.009, 0.01]
      "radius": 0.005
    - "center": [0.011, 0.003, -0.007]
      "radius": 0.005
    - "center": [0.021, 0.006, 0.007]
      "radius": 0.005
    - "center": [0.011, 0.003, 0.007]
      "radius": 0.005
    - "center": [0.021, 0.006, -0.007]
      "radius": 0.005
  - gripper_r_base_link:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.05]
      "radius": 0.02
    - "center": [0.0, -0.015, 0.03]
      "radius": 0.015
    - "center": [0.0, 0.015, 0.03]
      "radius": 0.015
    - "center": [0.063, 0.01, 0.003]
      "radius": 0.01
    - "center": [0.063, -0.01, 0.003]
      "radius": 0.01
    - "center": [0.089, -0.01, 0.017]
      "radius": 0.01
    - "center": [0.089, 0.01, 0.017]
      "radius": 0.01
  - gripper_r_inner_link1:
    - "center": [0.0, 0.003, -0.005]
      "radius": 0.01
    - "center": [0.0, 0.003, 0.005]
      "radius": 0.01
    - "center": [0.014, 0.012, -0.005]
      "radius": 0.00758
    - "center": [0.014, 0.012, 0.006]
      "radius": 0.00758
    - "center": [0.025, 0.019, 0.008]
      "radius": 0.00574
    - "center": [0.015, -0.008, 0.02]
      "radius": 0.005
    - "center": [0.015, -0.008, -0.02]
      "radius": 0.005
    - "center": [0.051, -0.008, 0.012]
      "radius": 0.005
    - "center": [0.051, -0.008, -0.012]
      "radius": 0.005
    - "center": [0.024, -0.008, 0.018]
      "radius": 0.005
    - "center": [0.033, -0.008, 0.016]
      "radius": 0.005
    - "center": [0.042, -0.008, 0.014]
      "radius": 0.005
    - "center": [0.024, -0.008, -0.018]
      "radius": 0.005
    - "center": [0.033, -0.008, -0.016]
      "radius": 0.005
    - "center": [0.042, -0.008, -0.014]
      "radius": 0.005
    - "center": [0.033, -0.008, 0.004]
      "radius": 0.005
    - "center": [0.033, -0.008, -0.004]
      "radius": 0.005
  - gripper_r_outer_link1:
    - "center": [0.007, -0.004, -0.004]
      "radius": 0.01
    - "center": [0.007, -0.004, 0.005]
      "radius": 0.01
    - "center": [0.033, -0.017, -0.004]
      "radius": 0.005
    - "center": [0.033, -0.017, 0.007]
      "radius": 0.005
    - "center": [0.015, -0.008, -0.004]
      "radius": 0.00841
    - "center": [0.028, -0.014, -0.004]
      "radius": 0.00595
    - "center": [0.015, -0.008, 0.005]
      "radius": 0.00841
    - "center": [0.028, -0.014, 0.007]
      "radius": 0.00595
    - "center": [0.015, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.015, 0.008, -0.02]
      "radius": 0.005
    - "center": [0.049, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.049, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, -0.02]
      "radius": 0.005
    - "center": [0.032, 0.007, -0.02]
      "radius": 0.005
    - "center": [0.04, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.007, 0.02]
      "radius": 0.005
    - "center": [0.04, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.008, 0.01]
      "radius": 0.005
    - "center": [0.024, 0.008, -0.01]
      "radius": 0.005
    - "center": [0.032, 0.007, 0.0]
      "radius": 0.005
  - gripper_r_inner_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.008
    - "center": [0.017, -0.014, 0.0]
      "radius": 0.008
    - "center": [0.009, -0.007, 0.0]
      "radius": 0.008
  - gripper_r_outer_link3:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.008
    - "center": [0.018, 0.014, 0.0]
      "radius": 0.008
    - "center": [0.009, 0.007, 0.0]
      "radius": 0.008
  - gripper_r_inner_link4:
    - "center": [0.013, -0.008, 0.004]
      "radius": 0.008
    - "center": [0.013, -0.008, -0.004]
      "radius": 0.008
    - "center": [0.046, -0.021, -0.0]
      "radius": 0.002
    - "center": [0.042, -0.02, 0.008]
      "radius": 0.002
    - "center": [0.042, -0.02, -0.008]
      "radius": 0.002
    - "center": [0.024, -0.013, -0.006]
      "radius": 0.00566
    - "center": [0.032, -0.016, -0.007]
      "radius": 0.004
    - "center": [0.038, -0.018, -0.008]
      "radius": 0.00283
    - "center": [0.024, -0.013, 0.006]
      "radius": 0.00566
    - "center": [0.032, -0.016, 0.007]
      "radius": 0.004
    - "center": [0.038, -0.018, 0.008]
      "radius": 0.00283
    - "center": [0.044, -0.02, 0.004]
      "radius": 0.002
    - "center": [0.044, -0.02, -0.004]
      "radius": 0.002
    - "center": [0.036, -0.018, -0.0]
      "radius": 0.004
  - gripper_r_outer_link4:
    - "center": [0.005, 0.005, 0.0]
      "radius": 0.01
    - "center": [0.014, 0.007, -0.022]
      "radius": 0.008
    - "center": [0.014, 0.007, 0.022]
      "radius": 0.008
    - "center": [0.046, 0.021, -0.0]
      "radius": 0.0013
    - "center": [0.033, 0.019, -0.025]
      "radius": 0.004
    - "center": [0.033, 0.019, 0.025]
      "radius": 0.004
    - "center": [0.021, 0.011, -0.0]
      "radius": 0.00665
    - "center": [0.032, 0.016, -0.0]
      "radius": 0.00442
    - "center": [0.039, 0.018, -0.0]
      "radius": 0.00294
    - "center": [0.043, 0.02, -0.0]
      "radius": 0.00196
    - "center": [0.038, 0.02, -0.016]
      "radius": 0.00302
    - "center": [0.042, 0.021, -0.009]
      "radius": 0.00228
    - "center": [0.044, 0.021, -0.004]
      "radius": 0.00172
    - "center": [0.038, 0.02, 0.016]
      "radius": 0.00302
    - "center": [0.042, 0.021, 0.009]
      "radius": 0.00228
    - "center": [0.044, 0.021, 0.004]
      "radius": 0.00172
    - "center": [0.025, 0.014, 0.025]
      "radius": 0.00566
    - "center": [0.025, 0.014, -0.025]
      "radius": 0.00566
    - "center": [0.028, 0.016, 0.014]
      "radius": 0.00516
    - "center": [0.028, 0.016, -0.014]
      "radius": 0.00516
  - gripper_r_inner_link2:
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.005
    - "center": [0.033, -0.011, -0.012]
      "radius": 0.005
    - "center": [0.033, -0.011, 0.012]
      "radius": 0.005
    - "center": [0.0, 0.0, -0.01]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.005
    - "center": [0.008, -0.003, -0.018]
      "radius": 0.005
    - "center": [0.016, -0.005, -0.016]
      "radius": 0.005
    - "center": [0.024, -0.008, -0.014]
      "radius": 0.005
    - "center": [0.008, -0.003, 0.018]
      "radius": 0.005
    - "center": [0.016, -0.005, 0.016]
      "radius": 0.005
    - "center": [0.024, -0.008, 0.014]
      "radius": 0.005
    - "center": [0.033, -0.011, -0.004]
      "radius": 0.005
    - "center": [0.033, -0.011, 0.004]
      "radius": 0.005
    - "center": [0.011, -0.004, -0.009]
      "radius": 0.005
    - "center": [0.022, -0.007, 0.001]
      "radius": 0.005
    - "center": [0.011, -0.004, 0.009]
      "radius": 0.005
    - "center": [0.022, -0.007, -0.001]
      "radius": 0.005
  - gripper_r_outer_link2:
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.009, -0.02]
      "radius": 0.005
    - "center": [0.032, 0.008, 0.02]
      "radius": 0.005
    - "center": [0.0, 0.0, -0.01]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.005
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.005
    - "center": [0.008, 0.002, -0.02]
      "radius": 0.005
    - "center": [0.016, 0.004, -0.02]
      "radius": 0.005
    - "center": [0.024, 0.006, -0.02]
      "radius": 0.005
    - "center": [0.008, 0.002, 0.02]
      "radius": 0.005
    - "center": [0.016, 0.004, 0.02]
      "radius": 0.005
    - "center": [0.024, 0.006, 0.02]
      "radius": 0.005
    - "center": [0.032, 0.009, -0.01]
      "radius": 0.005
    - "center": [0.032, 0.009, 0.0]
      "radius": 0.005
    - "center": [0.032, 0.009, 0.01]
      "radius": 0.005
    - "center": [0.011, 0.003, -0.007]
      "radius": 0.005
    - "center": [0.021, 0.006, 0.007]
      "radius": 0.005
    - "center": [0.011, 0.003, 0.007]
      "radius": 0.005
    - "center": [0.021, 0.006, -0.007]
      "radius": 0.005
