# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - idx01_body_joint1
default_q: [
    0.0
]

acceleration_limits: [
   10
]

jerk_limits: [
   10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: idx02_body_joint2, rule: fixed, value: -0.0}
    - {name: idx03_body_joint3, rule: fixed, value: -0.0}
    - {name: idx04_body_joint4, rule: fixed, value: 0.0008}
    - {name: idx05_body_joint5, rule: fixed, value: -0.0}
    - {name: idx21_arm_l_joint1, rule: fixed, value: 0.001}
    - {name: idx61_arm_r_joint1, rule: fixed, value: -0.0017}
    - {name: idx22_arm_l_joint2, rule: fixed, value: -1e-04}
    - {name: idx62_arm_r_joint2, rule: fixed, value: 0.0006}
    - {name: idx23_arm_l_joint3, rule: fixed, value: -0.0002}
    - {name: idx63_arm_r_joint3, rule: fixed, value: -0.0014}
    - {name: idx24_arm_l_joint4, rule: fixed, value: 0.012}
    - {name: idx64_arm_r_joint4, rule: fixed, value: -0.0026}
    - {name: idx25_arm_l_joint5, rule: fixed, value: -0.0031}
    - {name: idx65_arm_r_joint5, rule: fixed, value: -0.0023}
    - {name: idx26_arm_l_joint6, rule: fixed, value: -0.0069}
    - {name: idx66_arm_r_joint6, rule: fixed, value: 0.0049}
    - {name: idx27_arm_l_joint7, rule: fixed, value: -0.0008}
    - {name: idx67_arm_r_joint7, rule: fixed, value: 0.0036}
    - {name: idx31_gripper_l_inner_joint1, rule: fixed, value: -46.1668}
    - {name: idx39_gripper_l_inner_joint2, rule: fixed, value: 0.0883}
    - {name: idx41_gripper_l_outer_joint1, rule: fixed, value: 15.0526}
    - {name: idx49_gripper_l_outer_joint2, rule: fixed, value: 0.1154}
    - {name: idx71_gripper_r_inner_joint1, rule: fixed, value: -35.9971}
    - {name: idx79_gripper_r_inner_joint2, rule: fixed, value: 0.0197}
    - {name: idx81_gripper_r_outer_joint1, rule: fixed, value: 49.9705}
    - {name: idx89_gripper_r_outer_joint2, rule: fixed, value: 0.0244}
    - {name: idx32_gripper_l_inner_joint3, rule: fixed, value: 120.7102}
    - {name: idx42_gripper_l_outer_joint3, rule: fixed, value: -28.3124}
    - {name: idx72_gripper_r_inner_joint3, rule: fixed, value: 78.217}
    - {name: idx82_gripper_r_outer_joint3, rule: fixed, value: -67.0491}
    - {name: idx33_gripper_l_inner_joint4, rule: fixed, value: -0.002}
    - {name: idx43_gripper_l_outer_joint4, rule: fixed, value: -0.0079}
    - {name: idx73_gripper_r_inner_joint4, rule: fixed, value: 0.0013}
    - {name: idx83_gripper_r_outer_joint4, rule: fixed, value: -0.0041}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
